version: "3"

services:
  brezel-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/developer/brezel
    working_dir: /home/developer/brezel
    command: bash -c "mkdir -p build && cd build && cmake .. && cmake --build . --parallel $(nproc)"
    environment:
      - DISPLAY=${DISPLAY}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty: true
