# Summary.cmake - Print build configuration summary

# Define colors for terminal output
if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColorReset "${Esc}[m")
  set(ColorBold "${Esc}[1m")
  set(Red "${Esc}[31m")
  set(Green "${Esc}[32m")
  set(Yellow "${Esc}[33m")
  set(Blue "${Esc}[34m")
  set(Magenta "${Esc}[35m")
  set(Cyan "${Esc}[36m")
  set(White "${Esc}[37m")
  set(BoldRed "${Esc}[1;31m")
  set(BoldGreen "${Esc}[1;32m")
  set(BoldYellow "${Esc}[1;33m")
  set(BoldBlue "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan "${Esc}[1;36m")
  set(BoldWhite "${Esc}[1;37m")
else()
  set(ColorReset "")
  set(ColorBold "")
  set(Red "")
  set(Green "")
  set(Yellow "")
  set(Blue "")
  set(Magenta "")
  set(Cyan "")
  set(White "")
  set(BoldRed "")
  set(BoldGreen "")
  set(BoldYellow "")
  set(BoldBlue "")
  set(BoldMagenta "")
  set(BoldCyan "")
  set(BoldWhite "")
endif()

# Function to print YES/NO colorized
function(print_bool_option var_name var_value)
  if(${var_value})
    message(STATUS "  ${var_name}: ${BoldGreen}YES${ColorReset}")
  else()
    message(STATUS "  ${var_name}: ${BoldRed}NO${ColorReset}")
  endif()
endfunction()

# Print build configuration summary
message("\n${BoldBlue}===================== Brezel Configuration Summary =====================${ColorReset}")
message("\n${BoldCyan}General:${ColorReset}")
message(STATUS "  CMake version: ${CMAKE_VERSION}")
message(STATUS "  C++ Compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "  Build type: ${CMAKE_BUILD_TYPE}")
message(STATUS "  Install prefix: ${CMAKE_INSTALL_PREFIX}")

message("\n${BoldCyan}Build Options:${ColorReset}")
print_bool_option("Build tests" BREZEL_BUILD_TESTS)
print_bool_option("Build examples" BREZEL_BUILD_EXAMPLES)
print_bool_option("Build benchmarks" BREZEL_BUILD_BENCHMARKS)
print_bool_option("Build documentation" BREZEL_BUILD_DOCS)
print_bool_option("Compile extensions" BREZEL_COMPILE_EXTENSIONS)

message("\n${BoldCyan}Features:${ColorReset}")
print_bool_option("CUDA support" BREZEL_USE_CUDA)
print_bool_option("OpenMP support" BREZEL_USE_OPENMP)
print_bool_option("BLAS/LAPACK support" BREZEL_USE_BLAS)
print_bool_option("Eigen integration" BREZEL_USE_EIGEN)
print_bool_option("spdlog integration" BREZEL_USE_SPDLOG)
print_bool_option("Profiling" BREZEL_ENABLE_PROFILING)

if(DEFINED BREZEL_WITH_PCH)
  print_bool_option("Precompiled headers" BREZEL_WITH_PCH)
endif()

message("\n${BoldCyan}Developer Options:${ColorReset}")
print_bool_option("Warnings as errors" BREZEL_WARNINGS_AS_ERRORS)

if(DEFINED BREZEL_ENABLE_SANITIZER_ADDRESS)
  print_bool_option("Address sanitizer" BREZEL_ENABLE_SANITIZER_ADDRESS)
endif()

if(DEFINED BREZEL_ENABLE_SANITIZER_UNDEFINED)
  print_bool_option("UB sanitizer" BREZEL_ENABLE_SANITIZER_UNDEFINED)
endif()

if(DEFINED BREZEL_ENABLE_SANITIZER_THREAD)
  print_bool_option("Thread sanitizer" BREZEL_ENABLE_SANITIZER_THREAD)
endif()

message("\n${BoldBlue}=================================================================${ColorReset}\n")