name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{matrix.os}}-${{matrix.build_type}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libopenblas-dev libomp-dev
        shell: bash

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew install ninja openblas libomp llvm
          echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=$(brew --prefix llvm)" >> $GITHUB_ENV
        shell: bash

      - name: Install Windows Dependencies
        if: runner.os == 'Windows'
        run: |
          choco install ninja
        shell: powershell

      - name: Install vcpkg (Unix)
        if: runner.os != 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics
        shell: bash

      - name: Install vcpkg (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat -disableMetrics
        shell: cmd

      - name: Configure CMake (macOS)
        if: runner.os == 'macOS'
        run: |
          cmake -B build -S . \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DBREZEL_BUILD_TESTS=ON \
                -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp" \
                -DOpenMP_CXX_LIB_NAMES="omp" \
                -DOpenMP_omp_LIBRARY=$(brew --prefix libomp)/lib/libomp.dylib
        shell: bash

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: |
          cmake -B build -S . \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DBREZEL_BUILD_TESTS=ON
        shell: bash

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake -DBREZEL_BUILD_TESTS=ON
        shell: cmd

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}
        shell: bash

      - name: Test
        run: ctest -C ${{ matrix.build_type }} --output-on-failure
        working-directory: build
        shell: bash
