name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{matrix.os}}-${{matrix.build_type}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libopenblas-dev libomp-dev

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew install ninja openblas libomp

      - name: Clone vcpkg
        run: |
          if [ ! -d "${{ github.workspace }}/vcpkg" ]; then
             git clone https://github.com/microsoft/vcpkg.git ${{ github.workspace }}/vcpkg
             cd ${{ github.workspace }}/vcpkg
             git checkout 7f9f0e599e8f9d09e8c3993c677eef3a87b92495
           fi
        shell: bash

      - name: Bootstrap vcpkg
        run: |
          cd ${{ github.workspace }}/vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics
        if: runner.os != 'Windows'
        shell: bash

      - name: Bootstrap vcpkg (Windows)
        run: |
          cd ${{ github.workspace }}/vcpkg
          .\bootstrap-vcpkg.bat -disableMetrics
        if: runner.os == 'Windows'
        shell: cmd

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: "${{ github.workspace }}/vcpkg"
          vcpkgGitCommitId: "7f9f0e599e8f9d09e8c3993c677eef3a87b92495"

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DBREZEL_BUILD_TESTS=ON
        shell: bash

      - name: Build
        run: cmake --build ${{github.workspace }}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure
